### ISSUE TITLE
ports allocated to device are not returned to main pool

### ISSUE THREAD

**Issue by minghong** [openstf/stf#138]
lib/units/provider/index.js
function spawn(){
var allocatedPorts = ports.splice(0, 2)
          , proc = options.fork(device, allocatedPorts)
          , resolver = Promise.defer()
...
}
after options.fork(...), allocatedPorts become empty, so that the allocated ports can not be returned.
to fix it, we should pass value of allocatedPorts, not its reference.
 proc = options.fork(device, allocatedPorts.slice())

**Comment by sorccu** [comment]
You're right, this is caused by a relatively recent change (well, ~2-3 months) to the way ports are passed to the workers.

**Comment by sorccu** [comment]
This should now be fixed.

**Comment by minghong** [comment]
another issue:
some times the .finally() block in spawn() function is not executed.
I  moved the .finally() block after .catch() block, the .finally() block "finally" executed. 
I am not sure this is a bug in bluebird.

**Comment by sorccu** [comment]
Yes I know. I believe it's a bug in our code. Overall I'm not very happy with the provider unit right now, it needs a rewrite.

**Comment by Tierney0115** [comment]
Still have the same problem especially for Android 6.0 devices. 
I have 8 devices connected and four Android 6.0 devices met this problem after about 1 day. I can only restart the service to fix this error. Any idea to fix this? Thanks

**Comment by sorccu** [comment]
I would look into why the workers are restarting so much in the first place. It's possible that there's still a bug in our code, but if you encounter the bug after only 1 day, then the workers must be dying practically all the time. I'm pretty sure you said you were using an ODROID-XU4, but it's difficult to say anything without precise details about your system. You should tell us everything about your power adapter, the development board, the OS it's running, the output from `uname -a`, whether you're using a USB hub (and if so, which hub and which power adapter), and the USB cables you're using.

**Comment by Tierney0115** [comment]
Thank you for your reply.
I am using ODROID-XU4 with Odroid([Ubuntu 15.04](http://odroid.com/dokuwiki/doku.php?id=en:xu3_ubuntu_release_note_20150710))
The power adapter is 5V 4A
DIPO USB HUB 2.0 12V 5A adapter. 2A X 10 2.0 ports
The uname -a information is blow:
Linux odroid 3.10.82-39 #1 SMP PREEMPT Fri Jul 10 17:12:32 BRT 2015 armv7l armv7l armv7l GNU/Linux
So you think maybe USB  connection caused this problem?

**Comment by sorccu** [comment]
I'm not at home right now but I'm on Arch Linux and I'm pretty sure the kernel version is 3.10.92 or something. You might want to look into updating the kernel, there are USB-related fixes in basically every release. I'm also running Linux [4.2](http://odroid.com/dokuwiki/doku.php?id=en:xu4_building_kernel) on one of my other XU4s. It took about 10 minutes to crosscompile on a quad core i7 from 2014 or so. So far I have not done extensive testing with the newer kernel, but I would definitely give it a try given the amount of problems you have. Hardkernel will also attempt to provide Linux 4.4 once it becomes stable.

**Comment by Tierney0115** [comment]
I also have an other XU4 with the same system and connected 9 devices with the same USB Hub.
All the Android devices seem work fine for about a week and the only different is the XU4 don't have Android 6.0 connected. So I am not sure this is the kernel problem. Hope you could find this is kernel problem or not. 
Right now restarting service cannot solve the problem and there are two devices always show 
error missing required argument --screen-port
Since I am not at the same place with phones I cannot re plug it. And the adb devices show normally

**Comment by Tierney0115** [comment]
And also all the devices have flashed new ROM and rooted. They are using unofficial cables.

**Comment by sorccu** [comment]
I only have a single Android 6.0 device, a Nexus 9. It's running perfectly on my Arch Linux XU4, and it's connected directly to one of the USB 3 ports.

While we should certainly make sure that the `--screen-port` problem doesn't occur at all, getting the error means that the worker is dying practically all the time. Even if the error was fixed, the device would be practically unusable, since it would just die in the middle of a user session. Usually it indicates a weak USB connection, or that one of the services the worker requires isn't working properly. Even if you see the devices with `adb devices`, they could be losing connectivity momentarily.

I would suggest doing the following on the problematic provider:

1. Run `nc localhost 5037`
2. Write `0012host:track-devices`, hit enter and keep watching
3. Start the STF provider on that machine, and save the log output somewhere
4. If you start getting output from track-devices often, it means that some devices are getting dropped on ADB level. This could also be caused by bad socket handling on our side, causing ADB to reset the connection, though.

If it doesn't seem to work, I would need to see the whole log from the start, all the way from `stf provider ...` to until you start getting the `--screen-port` error. For an even more informative log, you can try setting the DEBUG environment variable to `*`, like this: `DEBUG=* stf provider ...`. You can find my email address in my profile if you'd rather send it privately.

You can also try running ADB with `ADB_TRACE=all adb start-server` to get more output from ADB side. You'll get a huge amount of information, though.

Anyway without proper logs I can only take random guesses, since it's working fine for me.

I would definitely try updating the kernel too. It's a relatively low effort thing to do, and might actually end up fixing the issue.

**Comment by sorccu** [comment]
Note that I don't necessarily mean that there's a bug in the Linux kernel. However, many USB devices/chips have vendor or even device specific workarounds hardcoded in the kernel. Since Linux 3.10 is originally from 2013, it could be that it simply doesn't have the necessary workarounds for your hardware. And then your Android 6.0 devices are somehow causing the issues to appear, that may otherwise have been fixed in newer kernels.

**Comment by Tierney0115** [comment]
Thank you for your advice. 

I have tracked devices and it seems not adb problem. I found the --screen-port error always shown on journalctl -u mystf.service, even I stop the service, so that I reboot all the servers and restart STF services. 

It is turned out the same error as #108 and #95. I am using the latest master code and tried three Android 6.0 devices, two of them have the error, the other one is fine. And also one Android 5.0 system has the same issue,too. I just checked all your commits relate to get compatibility for Android 6.0 and found issues under openstf minicap that some devices have error with the minicap. I am not sure why those error devices were successful the first time and got error after one day.  

Is this reason caused the problem and could you give me some debug hint about get compatibility for those "special" devices?

Sorry for bothering you again. Very appreciate.

**Comment by sorccu** [comment]
It's usually caused by manufacturer modifications of the private Android APIs minicap uses. I'm not sure if that's what happening in this case, I would have to see the logs. Anyway, it seems to mostly happen on Chinese devices, for some reason. Perhaps they like to customize their ROMs more. For other devices, I would say that overall less than 1% have this problem. Usually, fixing a problem on one device from the same manufacturer makes all other devices from that manufacturer work too, but there have been some exceptions.

Fortunately, though, it's usually possible to find some kind of a workaround for almost any device. However, it's almost impossible to do it without having access to the device. Furthermore, temporary access is not usually enough. If we lose access to a device, then it might stop working again at some point since we can't test it anymore.

Since the project is open source, we don't have the money to buy every device in the world. If you'd really like to get these devices working, consider becoming a [hardware sponsor](https://github.com/openstf/stf#sponsors-wanted).

**Comment by Tierney0115** [comment]
@sorccu 
This problem caused by unstable USB cable... Thank you for your help.
